[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
gray_matter = "0.2"
comrak = "0.29"
notify = "7.0.0"